### ISSUE TITLE
Error when running CREST on TS search

### ISSUE THREAD

**Issue by Bitumelourd** [crest-lab/crest#195]
Hello

I am having a problem when running CREST on the TS conformation search. Most of my calculations end well, but for some of them, they end on :

```
-----------------------
Multilevel Optimization
-----------------------

 -------------------------
 1. crude pre-optimization
 -------------------------
 running RMSDs...
 done.
 E lowest :     0.00000
```

I found this message in the logfile:

```
At line 1068 of file /home/conda/feedstock_root/build_artifacts/crest_1653057505696/work/src/confscript2_misc.f90
Fortran runtime error: End of file

Error termination. Backtrace:
#0  0x2ac871db38e5 in list_formatted_read_scalar
	at ../../../libgfortran/io/list_read.c:2308
#1  0x55e0dad85b22 in ???
#2  0x55e0dad85ec2 in ???
#3  0x55e0dad8b075 in ???
#4  0x55e0dad82067 in ???
#5  0x55e0dae7bc3e in ???
#6  0x55e0dad14340 in ???
#7  0x2ac87440b554 in ???
#8  0x55e0dad14370 in ???
```

I researched the previously reported issues, found this one https://github.com/crest-lab/crest/issues/171 and verified that my conda is up to date. I also tried another geometric input based on what CREST gave in the first round of iteration without success.

What would you suggest?

Thanks in advance

**Comment by Bitumelourd** [comment]
Thank you for your quick response!

I tried with the continuous release version and encountered new problems.

With the constraints file:
```
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source
crest              00000000012BC040  Unknown               Unknown  Unknown
crest              00000000006F3F50  Unknown               Unknown  Unknown
crest              00000000006F388F  Unknown               Unknown  Unknown
crest              0000000000673D24  simpletopo_               270  ztopology.f90
crest              00000000006719D5  simpletopo_file_           79  ztopology.f90
crest              00000000004A823C  inputcoords_             2291  confparse.f90
crest              0000000000491AF1  parseflags_               670  confparse.f90
crest              000000000068412B  MAIN__                     53  crest_main.f90
crest              0000000000402B0D  Unknown               Unknown  Unknown
crest              00000000012BE310  Unknown               Unknown  Unknown
crest              00000000004029EE  Unknown               Unknown  Unknown
```

Without the constraints file, CREST starts normally and ends with:
```
 -------------------------
 xTB Geometry Optimization
 -------------------------
 Geometry successfully optimized.
 WARNING! Change in topology detected!
 The topology change was seen in the initial geometry optimization.
 This could be an artifact of the chosen theory level (--gfn2).
 You can check the optimization trajectory in the "xtbopt.log" file.
 Try either of these options:

    A) Pre-optimize your input seperately with xtb and use the optimized
       structure as input for CREST. (Only recommended if structure is intact)

    B) Restart the same CREST call as before, but ignore the topology change
       by using the "--noreftopo" keyword. (May produce artifacts)

    C) Fix the initial input geometry by introducing bond length constraints
       or by using a method with fixed topology (GFN-FF).
 
abnormal termination of crest

```

**Comment by pprcht** [comment]
What's inside you constraints file? 
From the error message this seems to be some IO thing, but I can't tell what exactly breaks.

**Comment by Bitumelourd** [comment]
My constraints file is:

```
$constrain
atoms: 12, 13, 17
force constant=1
reference=struc.xyz
distance: 12, 13, auto
distance: 13, 17, auto
$metadyn
atoms: 1-11, 14-16, 18-22
$end
```

This is like my other TS conformational searches on CREST that end normally.

**Comment by pprcht** [comment]
hm ok, this doesn't really get me anywhere. Can you send me your input so I could try to reproduce it locally? You can do it via email if you don't want to post it here.
