### ISSUE TITLE
Initial geometry optimization failed

### ISSUE THREAD

**Issue by Jevon-Du** [crest-lab/crest#313]
Hello, 

I am trying to generate conformations for a cyclic peptide using crest v3.0.1, precompiled binary, commit (1782d7d), xtb version 6.6.1.  I get an error when using this command `crest xtbtopo.mol --gfn2 -g h2o -T 14`, but the program runs fine when using command `crest xtbtopo.mol --gfn2 -g chcl3 -T 14`. I don't know why. 
And I tried to use the crest version 2.12(Compatible with xTB version 6.4.0) and it worked fine.

The last two lines of stdout of command `crest xtbtopo.mol --gfn2 -g h2o -T 14` is
```
  Initial geometry optimization failed!
  Please check your input. 
```

[test.pdb](https://github.com/user-attachments/files/16011256/test.txt) is the original cyclic peptide structure.
[xtbopt.pdb](https://github.com/user-attachments/files/16011288/xtbopt.txt) and [xtbtopo.mol](https://github.com/user-attachments/files/16011290/xtbtopo.txt) are the cyclic peptide structures after geometry optimization using xtb 6.6.1. The geometry optimization commond is `xtb test.pdb --opt`. 
`xtbtopo.mol` was used as input file of crest v3.0.1. 
A xyz format of `xtbtopo.mol` was also used as input file, but I still got the same error as above.

PS: Please change the file suffix `txt` to the correct format, `test.txt` to `test.pdb`, `xtbopt.txt` to `xtbopt.pdb`, `xtbtopo.txt` to `xtbtopo.mol`.

**Comment by pprcht** [comment]
Hi,
since you get different performance for two different implicit solvents it quite possible is because the implicit solvation implementation in tblite is currently inconsistent with xtb, as mentioned e.g. here #312 
There is currently not too much I can do from this side, but I spoke to the tblite developers about it.
You could try using `--alpb water`. This may work, but be aware that the inconsistency is also present in this case.

**Comment by Jevon-Du** [comment]
Hi, 

Thank you for your reply. I tried using `--alpb water`(v3.0.1), but it doesn't work.  
OK, I will use crest v2.12 to complete my work.

Thanks again.

**Comment by satyabratamaiti** [comment]
Initially I optimised the structure with xtb using 
xtb psu_u_stack.xyz --opt extreme --gfn 2 --alpb water --chrg -1 --uhf 1
then I took the optimised xtbopt.xyz to run crest using:
crest  --gfn2 --alpb water --chrg -1 --uhf 1  -T 4 
but I am getting the error:Command line input:
 $ crest --gfn2 --alpb water --chrg -1 --uhf 1 -T 4

  --gfn2               : Use of GFN2-xTB requested.
  --alpb water : implicit solvation
  --chrg -1
  --uhf 1
  -T 4 (CPUs/Threads selected)

> Setting up backup calculator ... done.
 ----------------
 Calculation info
 ----------------
> User-defined calculation level:
 : xTB calculation via tblite lib
 : GFN2-xTB level
 :   Molecular charge    : -1
 :   UHF parameter       : 1
 :   Solvation model     : alpb
 :   Solvent             : water
 :   Fermi temperature   : 300.00000
 :   Accuracy            : 1.00000
 :   max SCC cycles      : 500


 -----------------------------
 Initial Geometry Optimization
 -----------------------------

  Initial geometry optimization failed!
  Please check your input and, if present, crestopt.log.
ERROR STOP 

Error termination. Backtrace:
#0  0xcecf70 in ???
#1  0xced219 in ???
#2  0xcee327 in ???
#3  0x97a09c in trialopt_warning_
	at /home/runner/work/crest/crest/src/algos/setuptest.f90:349
#4  0x9a6fcd in trialopt_calculator_
	at /home/runner/work/crest/crest/src/algos/setuptest.f90:312
#5  0x7d263c in trialopt_
	at /home/runner/work/crest/crest/src/legacy_wrappers.f90:341
#6  0x40e116 in crest
	at /home/runner/work/crest/crest/src/crest_main.f90:227
#7  0x408f7e in main
	at /home/runner/work/crest/crest/src/crest_main.f90:26
I am also attaching xipped file containing 
[files.zip](https://github.com/user-attachments/files/16993987/files.zip)
input xyz and optimized xyz file.
Please give any solution.
