### ISSUE TITLE
Can not run the examples/expl-4 and expl-9

### ISSUE THREAD

**Issue by zdworld** [crest-lab/crest#317]
Hello,
  i cannot run the expl-4 and expl-9, could it be a bug of some sort? 

error information:
```
Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x1408a504531f in ???
        at ./signal/../sysdeps/unix/sysv/linux/x86_64/libc_sigaction.c:0
#1  0x55f44a87ecb7 in get_xtb_constraint_block
        at /home/qzy03/tools/crest/src/parsing/parse_xtbinput.f90:141
#2  0x55f44a87ecb7 in __parse_xtbinput_MOD_parse_xtb_inputfile
        at /home/qzy03/tools/crest/src/parsing/parse_xtbinput.f90:85
#3  0x55f44a76e707 in parserc2_
        at /home/qzy03/tools/crest/src/confparse.f90:2272
#4  0x55f44a778082 in parseflags_
        at /home/qzy03/tools/crest/src/confparse.f90:2073
#5  0x55f44a43fe97 in crest
        at /home/qzy03/tools/crest/src/crest_main.f90:56
#6  0x55f44a43eece in main
        at /home/qzy03/tools/crest/src/crest_main.f90:26
```
```
Backtrace for this error:
#0  0xf82f904531f in ???
        at ./signal/../sysdeps/unix/sysv/linux/x86_64/libc_sigaction.c:0
#1  0x58690b25e1fd in xtblmo_
        at /home/qzy03/tools/crest/src/legacy_algos/protonate.f90:244
#2  0x58690b270bcb in protsmall_
        at /home/qzy03/tools/crest/src/legacy_algos/tautomerize.f90:230
#3  0x58690b272f7d in tautomerize_
        at /home/qzy03/tools/crest/src/legacy_algos/tautomerize.f90:93
#4  0x58690af909d4 in crest
        at /home/qzy03/tools/crest/src/crest_main.f90:153
#5  0x58690af8eece in main
        at /home/qzy03/tools/crest/src/crest_main.f90:26
```

system information:
```
OS: Ubuntu 24.04 LTS x86_64
Kernel: 6.8.0-38-generic
CPU: Intel Xeon E5-2683 v4 (32) @ 3.000GHz x2
```
CREST  info:
```
Version:3.0.2
commit:(bf4e605) compiled by '@x99qzy03'
compiler:GNU (gcc 10.3.0)
build system:cmake-3.28.3
linear algebra backend: openblas
```

Thank you,
WuHan

**Comment by pprcht** [comment]
So the first issue in expl-4 I unfortunately can't reproduce.
The second one for expl-9 I could, this seems some gcc related issue, #318 should be the fix

**Comment by fuyulonggit** [comment]
@zdworld Hello, have you resolved the the error in expl-4?
