### ISSUE TITLE
CREST 3.0.2 error when using `force constant` or `reference` in xtbinput file in `constraints`

### ISSUE THREAD

**Issue by jevandezande** [crest-lab/crest#358]
Received the following error when `force constant` in `xtbinput`:

``` 
<xtbinput> file present.
 content of the constraining file (sorted):
> $constrain
>   force constant=2
>   distance: 2, 3, auto
Fortran runtime error: Integer overflow when calculating the amount of memory to allocate

Error termination. Backtrace:
#0  0x593574354e0b in read_xtbdatablock
	at /usr/local/src/conda/crest-3.0.2/src/parsing/parse_xtbinput.f90:719
#1  0x593574354e0b in __parse_xtbinput_MOD_parse_xtb_input_fallback
	at /usr/local/src/conda/crest-3.0.2/src/parsing/parse_xtbinput.f90:657
#2  0x593574354f50 in __parse_xtbinput_MOD_parse_xtb_inputfile
	at /usr/local/src/conda/crest-3.0.2/src/parsing/parse_xtbinput.f90:75
#3  0x593574232650 in parserc2_
	at /usr/local/src/conda/crest-3.0.2/src/confparse.f90:2290
#4  0x593574236718 in parseflags_
	at /usr/local/src/conda/crest-3.0.2/src/confparse.f90:2091
#5  0x593573ec003c in crest
	at /usr/local/src/conda/crest-3.0.2/src/crest_main.f90:56
#6  0x593573ebf280 in main
	at /usr/local/src/conda/crest-3.0.2/src/crest_main.f90:26
```

Received the following error when `constraints` in `xtbinput`:
```
<xtbinput> file present.
 content of the constraining file (sorted):
> $constrain
>   distance: 2, 3, auto
>   reference=ref_coord.xyz

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x74757a64531f in ???
	at ./signal/../sysdeps/unix/sysv/linux/x86_64/libc_sigaction.c:0
#1  0x74757a7a1372 in __memmove_avx512_unaligned_erms
	at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:364
#2  0x619f7fd2dcde in read_xtbdatablock
	at /usr/local/src/conda/crest-3.0.2/src/parsing/parse_xtbinput.f90:719
#3  0x619f7fd2dcde in __parse_xtbinput_MOD_parse_xtb_input_fallback
	at /usr/local/src/conda/crest-3.0.2/src/parsing/parse_xtbinput.f90:657
#4  0x619f7fd2df50 in __parse_xtbinput_MOD_parse_xtb_inputfile
	at /usr/local/src/conda/crest-3.0.2/src/parsing/parse_xtbinput.f90:75
#5  0x619f7fc0b650 in parserc2_
	at /usr/local/src/conda/crest-3.0.2/src/confparse.f90:2290
#6  0x619f7fc0f718 in parseflags_
	at /usr/local/src/conda/crest-3.0.2/src/confparse.f90:2091
#7  0x619f7f89903c in crest
	at /usr/local/src/conda/crest-3.0.2/src/crest_main.f90:56
#8  0x619f7f898280 in main
	at /usr/local/src/conda/crest-3.0.2/src/crest_main.f90:26
```

Runs correctly in xtb 6.7 (`xtb input.xyz -I xtbinput`)

**To Reproduce**
`crest input.toml`

`input.toml`
```
input = "input.xyz"
runtype = "optimize"
constraints = "xtbinput"
```

`xtbinput`
```
$constrain
    force constant=2
    distance: 2, 3, auto
    reference=ref_coord.xyz
$end
```

`input.xyz`/`ref_coord.xyz` (a stretched butane molecule)
```
14

C    -2.0382494900    0.3413854500    0.3514324400
C    -0.6168510900    0.0063518800    0.7743087400
C     0.6293128100   -0.0064800100   -0.7899518000
C     2.0507111500   -0.3415140800   -0.3670753800
H    -2.7021877800    0.3428943800    1.2215504600
H    -2.0861187000    1.3309810200   -0.1141398900
H    -2.4182679700   -0.3943035000   -0.3645945800
H    -0.6091424800   -0.9739967000    1.2648571700
H    -0.2788628600    0.7415707700    1.5139014700
H     0.6216034300    0.9738685500   -1.2804995800
H     0.2913243800   -0.7416993400   -1.5295441200
H     2.0985806000   -1.3311082100    0.0984993600
H     2.4307301000    0.3941752300    0.3489511300
H     2.7146499200   -0.3430236300   -1.2371931100
```

![image](https://github.com/user-attachments/assets/58829e74-d2fc-4d53-bc5d-e0b23637d000)

**Comment by pprcht** [comment]
which 3.0.2, a prebuilt binary from GitHub, the conda version, or self-built?

**Comment by pprcht** [comment]
Ah, sorry it's conda, I can see from the error backtrace.
The fix for this issue was already uploaded in commit 5ca82feb2ec4df30a0129db957163c934f085952, but since the conda version is not built from the main branch, it will not be updated until the next manual conda update (i.e. 3.0.3).

**Comment by sara2512** [comment]
Is it correct to assume that this problem is still existent in the most current conda version? We had the same errors with gfnff calculations on SUSE Linux from the conda build, but non when installing directly from the repo. 
@thevro I think this might be the reason for the problems we saw.

**Comment by pprcht** [comment]
@sara2512 yes, the issue is still persisting on conda, I haven't found the time to update to a new version yet. Sorry!

**Comment by mboggiop** [comment]
Would it be possible to have this bug fixed on the latest conda version? I have seen that the last post about this problem dates back to over a year.

**Comment by pprcht** [comment]
yes, working on it. Trying to coordinate with better g-xTB implementation.
